Add command-line option to disable logs (closes #48)
johang/btfs pull request #82
Opened 2023-12-19 04:38 UTC by DrDub

Set the logger to `/dev/null` when run with `-s` or `--silent`.

2023-12-19 15:04 UTC, johang commented
Can you add `--slient` to the man page (`man/btfs.1`) too?

2023-12-19 15:05 UTC, johang requested changes

2023-12-19 15:05 UTC, johang commented on src/btfs.cc
> +                printf("No logs.\n");
I don't like this print. Silent should be no prints.

2023-12-19 15:05 UTC, johang commented on src/btfs.h
> +       Log(std::string p) : std::ofstream(p.empty() ? "/dev/null" : p.c_str()), path(p) {
Indent with tab here like rest of the code.

2023-12-19 15:05 UTC, johang commented on src/btfs.cc
> +               new Log(params.silent ? std::string() : (p->save_path + "/../log.txt")));
Indent with tab here like rest of the code.

2023-12-20 00:21 UTC, DrDub commented on src/btfs.cc
> +                printf("No logs.\n");
Will drop it

2023-12-20 00:21 UTC, DrDub commented on src/btfs.h
> +       Log(std::string p) : std::ofstream(p.empty() ? "/dev/null" : p.c_str()), path(p) {
Sure. Missed that on my editor.

2023-12-21 09:48 UTC, merged

2023-12-21 09:48 UTC, johang commented
Thanks!